spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.0.250:3306/device_server?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Taipei
#    url: jdbc:mysql://localhost:3306/device_server?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Taipei
#    username: root
#    password: device@123
#    url: jdbc:mysql://154.82.110.72:3306/device_server?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
#    username: cejava_admin
#    password: NUbh6mI8y@P^
#  jpa:
#    database: mysql
#    show-sql: true
#    generate-ddl: true
#    hibernate:
##      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    database: 8
#    host: 192.168.0.250
    host: 156.251.17.184
    port: 6379
#    password: taiko12345
    password: Passw0rd@1688.gd
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
server:
  port: 8083

