spring:
  redis:
    database: 8
#    host: 192.168.0.250
    host: 156.251.17.184
    port: 6379
#    password: taiko12345
    password: Passw0rd@1688.gd
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
server:
  port: 8083

